server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
      routes:
        - id: payment_routh #payment_route
#          uri: http://localhost:8001
          uri: lb:http://cloud-payment-service
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2 #payment_route
          uri: lb:http://cloud-payment-service
#          uri: http://lcoalhost:8001
          predicates:
            - Path=/payment/lb/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka